"""
baseline_normalization.py — is a customer's refund behavior abnormal
relative to customers with SIMILAR ORDER VOLUME?
================================================================================
PHASE 2 of the top-5% upgrade program. Builds on Phase 1 (Pareto concentration)
by answering the question Phase 1 raises: concentration tells us WHERE the
exposure is, but not whether any individual customer's behavior is abnormal
FOR THEIR ACTIVITY LEVEL.

The core problem with the existing risk score:
    The eligibility rule (>=5 orders AND >30% refund rate) doesn't ask
    "30% compared with WHAT?" A customer with 5 orders and 2 refunds (40%)
    might be normal variance; a customer with 30 orders and 12 refunds (40%)
    is a different story. This script builds the population reference bands
    that make that distinction quantitative.

Method:
    1. Assign each customer to an order-volume band (1-2, 3-5, 6-10, 11-20, 21+)
    2. Within each band, compute the refund-rate distribution (mean, median,
       P75, P90, P95)
    3. For each customer, compute their refund rate and compare it against
       their band's distribution
    4. Flag customers whose refund rate exceeds their band's P95 as
       "above-baseline" — a NORMALIZED signal, distinct from the existing
       raw risk score

CRITICAL DISTINCTIONS (non-negotiable):
    - Activity level (how many orders) ≠ refund frequency (how many refunds)
      ≠ risk score (the composite heuristic)
    - Above-baseline ≠ fraudulent. It means "statistically unusual for the
      customer's volume band" — a prioritization signal only.
    - The existing risk score is NOT replaced; this analysis CHALLENGES it.

Run:  python scripts/baseline_normalization.py
Writes: reports/baseline_normalization.md
"""
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "processed" / "zomato_with_refunds.csv"
SUSPECTS = ROOT / "reports" / "fraud_suspects.csv"
REPORT = ROOT / "reports" / "baseline_normalization.md"

BANDS = [(1, 2), (3, 5), (6, 10), (11, 20), (21, 10_000)]
BAND_LABELS = ["1-2 orders", "3-5 orders", "6-10 orders", "11-20 orders", "21+ orders"]


def assign_band(order_count: int) -> str:
    for (lo, hi), label in zip(BANDS, BAND_LABELS):
        if lo <= order_count <= hi:
            return label
    return BAND_LABELS[-1]


def build_baselines(df: pd.DataFrame) -> pd.DataFrame:
    """Per-band refund-rate distributions + per-customer baseline comparison."""
    cust = df.groupby("Customer_ID").agg(
        total_orders=("ID", "count"),
        total_refunds=("Refund_Requested", "sum"),
        total_refund_amount=("Refund_Amount", "sum"),
    ).reset_index()
    cust["refund_rate"] = (cust["total_refunds"] / cust["total_orders"] * 100).round(2)
    cust["volume_band"] = cust["total_orders"].apply(assign_band)

    # per-band distributions
    band_stats = []
    for label in BAND_LABELS:
        sub = cust[cust["volume_band"] == label]
        if len(sub) == 0:
            continue
        rates = sub["refund_rate"]
        band_stats.append({
            "band": label,
            "customers": len(sub),
            "mean_rate": rates.mean(),
            "median_rate": rates.median(),
            "p75": rates.quantile(0.75),
            "p90": rates.quantile(0.90),
            "p95": rates.quantile(0.95),
            "max_rate": rates.max(),
        })
    bands_df = pd.DataFrame(band_stats)

    # per-customer comparison against their band's P95
    band_p95 = dict(zip(bands_df["band"], bands_df["p95"]))
    cust["band_p95"] = cust["volume_band"].map(band_p95)
    cust["above_baseline"] = cust["refund_rate"] > cust["band_p95"]
    cust["rate_vs_p95"] = (cust["refund_rate"] - cust["band_p95"]).round(2)

    return cust, bands_df


def main() -> None:
    df = pd.read_csv(DATA)
    cust, bands = build_baselines(df)

    # how many flagged suspects are actually above-baseline?
    suspects = pd.read_csv(SUSPECTS)
    sus_ids = set(suspects["Customer_ID"])
    cust["is_flagged"] = cust["Customer_ID"].isin(sus_ids)

    flagged = cust[cust["is_flagged"]]
    flagged_above = flagged[flagged["above_baseline"]]
    flagged_below = flagged[~flagged["above_baseline"]]

    n_above_all = int(cust["above_baseline"].sum())

    lines = [
        "# Customer Baseline Normalization",
        "### Is a customer's refund behavior abnormal relative to customers with similar order volume?",
        "",
        "> Generated by `scripts/baseline_normalization.py` — every figure computed live from",
        "> the seeded dataset. This analysis CHALLENGES the existing risk score by asking:",
        "> \"30% refund rate — compared with WHAT?\"",
        "",
        "## Population reference bands (order-volume cohorts)",
        "",
        "| Band | Customers | Mean rate | Median | P75 | P90 | P95 | Max |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for _, b in bands.iterrows():
        lines.append(
            f"| {b['band']} | {int(b['customers']):,} | {b['mean_rate']:.1f}% | "
            f"{b['median_rate']:.1f}% | {b['p75']:.1f}% | {b['p90']:.1f}% | "
            f"**{b['p95']:.1f}%** | {b['max_rate']:.1f}% |"
        )
    lines += [
        "",
        "## What this reveals about the existing risk score",
        "",
        f"- The existing eligibility rule (≥5 orders AND >30% refund rate) flags "
        f"**{len(flagged):,} customers**.",
        f"- Of those, **{len(flagged_above):,} are above their band's P95** "
        f"({len(flagged_above)/len(flagged)*100:.1f}% of flagged) — genuinely "
        "unusual for their volume.",
        f"- **{len(flagged_below):,} flagged customers are BELOW their band's P95** "
        f"({len(flagged_below)/len(flagged)*100:.1f}%) — their refund rate is "
        "high in absolute terms but *not unusual for their order volume*. "
        "These are the false-positive candidates Phase 4 will investigate.",
        "",
        f"- Across the full population, **{n_above_all:,} customers** "
        f"({n_above_all/len(cust)*100:.1f}%) exceed their band's P95 — "
        "these are the *normalized* candidates, independent of the existing score.",
        "",
        "## Why this matters for fraud analytics",
        "",
        "1. **Activity ≠ fraud.** A customer with 30 orders and a 40% refund rate",
        "   may be a heavy user with bad delivery luck; a customer with 2 orders",
        "   and a 50% rate is probably just noise. The raw threshold (30%) can't",
        "   tell these apart — the volume-banded baseline can.",
        "2. **The existing score and the baseline agree on most customers** but",
        f"   diverge on {len(flagged_below):,} — that divergence is the "
        "false-positive surface, quantified.",
        "3. **Above-baseline ≠ fraudulent.** A customer above their band's P95 is",
        "   statistically unusual for their volume — a review-prioritization",
        "   signal, never proof of fraud. (Synthetic, seeded dataset.)",
        "",
        "## Feed into Phase 4 (false-positive analysis)",
        "",
        f"The {len(flagged_below):,} flagged-but-below-baseline customers are "
        "the starting set for the false-positive analysis: their profiles "
        "(order volume, refund count, reasons) will be examined to identify "
        "legitimate-customer scenarios the risk score mishandles.",
        "",
        "## Reproduce",
        "",
        "```bash",
        "python scripts/baseline_normalization.py   # regenerates this report",
        "pytest tests/test_baseline_normalization.py -v",
        "```",
    ]
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("Volume-band baselines:")
    print(bands.to_string(index=False))
    print(f"\nFlagged: {len(flagged):,} | Above baseline: {len(flagged_above):,} "
          f"({len(flagged_above)/len(flagged)*100:.1f}%) | "
          f"Below: {len(flagged_below):,} ({len(flagged_below)/len(flagged)*100:.1f}%)")
    print(f"Above baseline (all customers): {n_above_all:,}")
    print(f"Report: {REPORT}")


if __name__ == "__main__":
    main()
