"""
cohort_analysis.py — does suspicious refund behavior emerge early or late?
================================================================================
PHASE 7. Groups customers by first-order month, then tracks refund behavior
per cohort. Answers: "Does abuse start from the beginning, or does it develop
after a customer has been active for a while?"

Run:  python scripts/cohort_analysis.py
Writes: reports/cohort_analysis.md
"""
from pathlib import Path
import pandas as pd
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "processed" / "zomato_with_refunds.csv"
GT = ROOT / "data" / "processed" / "ground_truth_customer_risk.csv"
REPORT = ROOT / "reports" / "cohort_analysis.md"


def main() -> None:
    df = pd.read_csv(DATA)
    df["Order_Date"] = pd.to_datetime(df["Order_Date"], dayfirst=True)
    gt = pd.read_csv(GT, index_col="Customer_ID")["Planted_Risk"]

    # first order month = cohort
    first_order = df.groupby("Customer_ID")["Order_Date"].min()
    df["cohort_month"] = df["Customer_ID"].map(
        first_order.dt.to_period("M").astype(str))

    # per-cohort aggregates
    cohorts = df.groupby("cohort_month").agg(
        customers=("Customer_ID", "nunique"),
        orders=("ID", "count"),
        refunds=("Refund_Requested", "sum"),
        refund_amount=("Refund_Amount", "sum"),
    ).reset_index()
    cohorts["refund_rate"] = (cohorts["refunds"] / cohorts["orders"] * 100).round(2)
    cohorts["avg_refund"] = (cohorts["refund_amount"] / cohorts["refunds"].clip(lower=1)).round(0)
    cohorts["avg_orders_per_cust"] = (cohorts["orders"] / cohorts["customers"]).round(1)

    # planted-risk distribution per cohort
    df["planted"] = df["Customer_ID"].map(gt)
    risk_dist = df.groupby("cohort_month")["planted"].value_counts().unstack(fill_value=0)
    for col in ["High", "Medium", "Low"]:
        if col not in risk_dist.columns:
            risk_dist[col] = 0
    risk_dist["high_pct"] = (risk_dist["High"] / risk_dist.sum(axis=1) * 100).round(1)

    # monthly refund rate per cohort (does behavior change over time within a cohort?)
    cohort_monthly = df.groupby(["cohort_month", df["Order_Date"].dt.to_period("M").astype(str)]).agg(
        orders=("ID", "count"), refunds=("Refund_Requested", "sum")).reset_index()
    cohort_monthly.columns = ["cohort", "month", "orders", "refunds"]
    cohort_monthly["refund_rate"] = (cohort_monthly["refunds"] / cohort_monthly["orders"] * 100).round(2)
    cohort_monthly["months_since_start"] = (
        pd.to_datetime(cohort_monthly["month"]) - pd.to_datetime(cohort_monthly["cohort"])
    ).dt.days / 30.44

    lines = [
        "# Cohort Analysis — Refund Behavior by First-Order Month",
        "### Does suspicious refund behavior emerge early or after a customer has been active?",
        "",
        "> Generated by `scripts/cohort_analysis.py`. Customers grouped by first-order",
        "> month; refund behavior tracked per cohort.",
        "",
        "## Cohort summary",
        "",
        "| Cohort | Customers | Orders | Refunds | Refund rate | Avg refund | Avg orders/cust |",
        "|---|---|---|---|---|---|---|",
    ]
    for _, c in cohorts.iterrows():
        lines.append(
            f"| {c['cohort_month']} | {int(c['customers']):,} | {int(c['orders']):,} | "
            f"{int(c['refunds']):,} | {c['refund_rate']:.1f}% | ₹{c['avg_refund']:,.0f} | "
            f"{c['avg_orders_per_cust']:.1f} |")

    lines += [
        "",
        "## Planted high-risk share by cohort",
        "",
        "| Cohort | High-risk % |",
        "|---|---|",
    ]
    for idx, row in risk_dist.iterrows():
        lines.append(f"| {idx} | {row['high_pct']:.1f}% |")

    lines += [
        "",
        "## Key findings",
        "",
        f"1. **Refund rates are stable across cohorts** "
        f"({cohorts['refund_rate'].min():.1f}%–{cohorts['refund_rate'].max():.1f}%). "
        "On this synthetic dataset, refund behavior is generated per-customer "
        "and doesn't depend on when they joined.",
        "2. **Planted high-risk share is roughly uniform** across cohorts — "
        "the generator assigns risk independently of join date.",
        "3. **On real data**, this analysis would reveal whether abuse emerges "
        "in specific acquisition periods (e.g., a fraud ring joining during a "
        "promo month), which is a critical fraud-detection signal.",
        "4. **Method caveat:** synthetic, seeded dataset — the uniformity is "
        "by construction, not a finding about real customer behavior.",
        "",
        "## Reproduce",
        "",
        "```bash",
        "python scripts/cohort_analysis.py",
        "pytest tests/test_cohort_analysis.py -v",
        "```",
    ]
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(cohorts.to_string(index=False))
    print(f"\nReport: {REPORT}")


if __name__ == "__main__":
    main()
