"""
validate_risk_score.py — validates the refund-fraud risk score against the
planted ground truth
=============================================================================
THE STORY THIS SCRIPT TELLS:

The refund layer in this project is synthetic, generated by
notebooks/01_data_generation.ipynb with a fixed seed. Crucially, the generator
ASSIGNS each customer a planted risk category (3% High / 7% Medium / 90% Low)
and then generates their refund behaviour FROM it (High → 70% refund rate with
repetitive reasons; Medium → 20%; Low → 5%). The planted category is ground
truth — but the original project threw it away and never validated the score.

This script:
  1. RECOVERS the planted ground truth (seeded, verified against the committed
     dataset — Customer_ID assignment must match 100%).
  2. REPRODUCES the risk score exactly as the dashboard computes it.
  3. MEASURES what the score actually achieves: precision, recall, AUC — and
     the coverage cost of the >=5-order eligibility filter.
  4. WRITES reports/score_validation.md and saves the recovered labels to
     data/processed/ground_truth_customer_risk.csv.

Run:  python scripts/validate_risk_score.py
"""
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import MinMaxScaler

ROOT = Path(__file__).resolve().parents[1]
RAW_PATH = ROOT / "data" / "raw" / "Zomato Dataset.csv"
ORDERS_PATH = ROOT / "data" / "processed" / "zomato_with_refunds.csv"
GT_PATH = ROOT / "data" / "processed" / "ground_truth_customer_risk.csv"
REPORT_PATH = ROOT / "reports" / "score_validation.md"
REPORT_PATH.parent.mkdir(exist_ok=True)

RISK_WEIGHTS = {"Refund_Rate": 0.40, "Reason_Repetition_Rate": 0.30,
                "Refunds_Per_Day": 0.20, "Avg_Reason_Length": 0.10}


# ── 1. Recover the planted ground truth (exact generator replay) ─────────────
def recover_ground_truth() -> pd.Series:
    np.random.seed(42)
    n_customers = 10_000
    customer_ids = [f"CUST{str(i).zfill(5)}" for i in range(1, n_customers + 1)]
    assigned = np.random.choice(customer_ids, size=45_584)  # consumed by generator

    risk = {}
    for cust in customer_ids:
        r = np.random.random()
        risk[cust] = "High" if r < 0.03 else ("Medium" if r < 0.10 else "Low")
    return pd.Series(risk, name="Planted_Risk"), pd.Series(assigned)


# ── 2. Reproduce the dashboard's risk score ──────────────────────────────────
def build_risk_table(orders: pd.DataFrame) -> pd.DataFrame:
    cs = orders.groupby("Customer_ID").agg(
        Total_Orders=("ID", "count"),
        Total_Refunds=("Refund_Requested", "sum"),
        Total_Refund_Amount=("Refund_Amount", "sum"),
    ).reset_index()
    cs["Refund_Rate"] = (cs["Total_Refunds"] / cs["Total_Orders"] * 100).round(2)

    flagged = cs[(cs["Total_Orders"] >= 5) & (cs["Refund_Rate"] > 30)].copy()

    refund_df = orders[orders["Refund_Requested"] == True].copy()  # noqa: E712

    def top_reason_rate(g):
        if len(g) == 0:
            return 0.0
        return round(g["Refund_Reason"].value_counts().iloc[0] / len(g) * 100, 2)

    rr = (refund_df.groupby("Customer_ID")
          .apply(top_reason_rate).reset_index(name="Reason_Repetition_Rate"))
    flagged = flagged.merge(rr, on="Customer_ID", how="left")

    refund_df["Reason_Length"] = refund_df["Refund_Reason"].str.len()
    arl = refund_df.groupby("Customer_ID").agg(Avg_Reason_Length=("Reason_Length", "mean")).reset_index()
    flagged = flagged.merge(arl, on="Customer_ID", how="left")

    tl = refund_df.groupby("Customer_ID").agg(
        First=("Order_Date", "min"), Last=("Order_Date", "max"),
        Ref=("Refund_Requested", "count")).reset_index()
    tl["Days_Span"] = (tl["Last"] - tl["First"]).dt.days
    tl["Refunds_Per_Day"] = (tl["Ref"] / (tl["Days_Span"] + 1)).round(4)
    flagged = flagged.merge(tl[["Customer_ID", "Days_Span", "Refunds_Per_Day"]],
                            on="Customer_ID", how="left")

    signals = list(RISK_WEIGHTS)
    flagged[signals] = flagged[signals].fillna(0)
    scaler = MinMaxScaler(feature_range=(0, 100))
    scaled = pd.DataFrame(scaler.fit_transform(flagged[signals]),
                          columns=[f"Score_{c}" for c in signals], index=flagged.index)
    flagged["Fraud_Risk_Score"] = sum(
        scaled[f"Score_{c}"] * w for c, w in RISK_WEIGHTS.items()).round(2)
    flagged["Risk_Tier"] = pd.cut(flagged["Fraud_Risk_Score"],
                                  bins=[-1, 40, 70, 100],
                                  labels=["Low", "Medium", "High"])
    return flagged.sort_values("Fraud_Risk_Score", ascending=False).reset_index(drop=True)


def main():
    gt, assigned = recover_ground_truth()

    orders = pd.read_csv(ORDERS_PATH)
    orders["Order_Date"] = pd.to_datetime(orders["Order_Date"], dayfirst=True)

    # ── Verification: recovered Customer_ID assignment must match 100% ────────
    match = (assigned.values == orders["Customer_ID"].values).mean()
    assert match == 1.0, (
        f"Ground-truth recovery failed: Customer_ID match only {match:.1%}. "
        "The committed dataset was not generated by the seeded notebook.")
    print(f"Ground-truth recovery verified: Customer_ID match 100% ✓")

    # Save labels for tests / future work
    gt.rename_axis("Customer_ID").to_csv(GT_PATH)

    suspects = build_risk_table(orders)
    suspects["Planted_Risk"] = suspects["Customer_ID"].map(gt)

    # ── Metrics ───────────────────────────────────────────────────────────────
    n_planted_high = int((gt == "High").sum())
    pool = suspects
    in_pool_high = int((pool["Planted_Risk"] == "High").sum())
    coverage = in_pool_high / n_planted_high

    high_tier = pool[pool["Risk_Tier"] == "High"]
    tp = int((high_tier["Planted_Risk"] == "High").sum())
    precision = tp / len(high_tier) if len(high_tier) else float("nan")
    recall = tp / n_planted_high

    y = (pool["Planted_Risk"] == "High").astype(int)
    auc = roc_auc_score(y, pool["Fraud_Risk_Score"])

    # ── Report ────────────────────────────────────────────────────────────────
    lines = [
        "# Risk Score Validation — against the planted ground truth",
        "",
        "> Generated by `scripts/validate_risk_score.py`. The refund layer is synthetic;",
        "> its generator *assigns* each customer a planted risk category (3% High, 7%",
        "> Medium, 90% Low) and generates refund behaviour from it. This script recovers",
        "> those labels (verified: Customer_ID assignment matches the committed dataset",
        "> 100%) and measures what the risk score actually achieves.",
        "",
        "## Headline results",
        "",
        "| Metric | Value | What it means |",
        "|---|---|---|",
        f"| Planted High-risk customers | **{n_planted_high}** | The 'fraudsters' by construction |",
        f"| Eligible pool size (≥5 orders & >30% refund rate) | {len(pool)} | The pipeline only scores these |",
        f"| Planted High inside the pool | {in_pool_high} ({coverage:.1%}) | **Coverage gap: the eligibility filter excludes {1-coverage:.0%} of fraudsters** |",
        f"| High tier (score > 70) size | {len(high_tier)} | What the fraud team would investigate first |",
        f"| Precision of High tier | **{precision:.1%}** | Of {len(high_tier)} investigated, {tp} are planted fraudsters |",
        f"| Recall of High tier (vs all planted High) | **{recall:.1%}** | The full funnel catches {tp} of {n_planted_high} |",
        f"| AUC of score vs planted High (in pool) | **{auc:.3f}** | Ranking quality within the eligible pool |",
        "",
        "## The honest reading",
        "",
        f"1. **The score ranks well.** Within the eligible pool the score separates",
        f"   planted fraudsters from the rest at AUC {auc:.2f}, and everyone in the top",
        f"   tier is a planted fraudster — precision {precision:.0%}.",
        f"2. **The funnel leaks badly.** The ≥5-order eligibility filter removes",
        f"   {1-coverage:.0%} of planted fraudsters before scoring even begins (the dataset",
        "   averages ~4.6 orders per customer, so most customers never reach 5 orders).",
        f"   End-to-end recall is only {recall:.0%}.",
        "3. **Design lesson (the real takeaway):** an eligibility threshold trades",
        "   coverage for confidence. A production design would either score every",
        "   customer with ≥1 refund, or use a two-stage funnel (score all, then",
        "   prioritize) — and would report end-to-end recall, not just in-pool metrics.",
        "",
        "## Why these numbers are achievable at all",
        "",
        "The generator *plants* the fraud signal (70% vs 20% vs 5% refund rates,",
        "repetitive 'Item Not Received' reasons). Real refund-fraud detection has no",
        "ground truth this clean — validation there means investigator outcomes over",
        "months. The pipeline demonstrated here is the method; the performance numbers",
        "are a property of the synthetic setup, not a claim about real detection power.",
        "",
        "## Reproduce",
        "",
        "```bash",
        "python scripts/validate_risk_score.py   # regenerates this report + labels",
        "pytest tests/ -q                        # consistency tests pin all of this",
        "```",
    ]
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"\nPool: {len(pool)} | Planted High in pool: {in_pool_high}/{n_planted_high} "
          f"({coverage:.1%})")
    print(f"High tier: {len(high_tier)} | precision {precision:.1%} | "
          f"end-to-end recall {recall:.1%} | in-pool AUC {auc:.3f}")
    print(f"\nReport: {REPORT_PATH}")
    print(f"Labels: {GT_PATH}")


if __name__ == "__main__":
    main()
